package atlas.core.template.datatables;

import java.util.Collection;
import java.util.Map;
import java.util.function.Function;

/**
 * @category    Datatables
 * @package     Dev
 * @since       Nov 05, 2018
 * @author      Ignatius
 * @version     1.0.0
 */
public interface DataTablesInterfaceV2 {

    /**
     * When one just wants to return an empty result set
     *
     * @return Map<String, Object>
     */
    public Map<String, Object> emptyResultSet();

    /**
     * Indicate whether we have prepared a native sql statement
     *
     * @param state
     * @return DataTableV2
     */
    public DataTableV2 nativeSQL(boolean state);

    /**
     * Called to re-initialise the parameters as the class is ever on
     */
    /**
     * Specify the columns that will appear in the final result set in order to
     * assist this class in building the information needed to render the
     * DataTableV2 result map
     *
     * @param select
     * @return DataTableV2sInterface
     */
    public DataTableV2 select(String select);

    /**
     * Specify the tables where the information will be fetched from i.e. the
     * parent table and all the respective joins
     *
     * @param from
     * @return DataTableV2
     */
    public DataTableV2 from(String from);

    /**
     * Specify the conditions that will be applied to the query. This will help
     * in building the filter used by DataTableV2sInterfaces
     *
     * @param where
     * @return DataTableV2
     */
    public DataTableV2 where(String where);

    /**
     * Apply the group by clause in order to properly support the aggregate
     * functions
     *
     * @param groupBy
     * @return DataTableV2
     */
    public DataTableV2 groupBy(String groupBy);

    /**
     * Set the formatter that will be used to format the response generated by
     * the class
     *
     * @param formatter
     * @return DataTableV2
     */
    public DataTableV2 setFormatter(RowFormatInterface formatter);

    /**
     * Set the parameter bound to the parameterised query passed in the
     * conditions
     *
     * @param key
     * @param value
     * @return DataTableV2
     */
    public DataTableV2 setParameter(String key, Object value);

    /**
     * Bind multiple values to a named query parameter.
     *
     * @param key
     * @param value
     * @return DataTableV2
     */
    public DataTableV2 setParameterList(String key, Collection value);

    /**
     * Allow one to add multiple parameters
     *
     * @param map
     * @return DataTableV2
     */
    public DataTableV2 setParameters(Map<String, Object> map);

    /**
     * Get the HQL that will be used to generate the result set
     *
     * @param setting
     * @return String
     */
    public String getHQL(String setting);

    /**
     * Get the parameters used to generate the result set
     *
     * @return  Map<String, Object>
     */
    public Map<String, Object> getParameters();

    /**
     * The following function generates the map used to render the result set
     *
     * @return Map<String, Object>
     */
    public Map<String, Object> showTable();

    /**
     * The following function generates the map used to render the result set
     *
     * @return Map<String, Object>
     */
    public Map<String, Object> showTable(Function<Object[], Object[]> func);

    /**
     *Allow one to specify the columns for footer totals
     *
     * @param key
     * @param columnName
     * @return DataTableV2
     */
    public DataTableV2 setFooterColumn(String key, String columnName);

    /**
     * Allow one to specify the columns to order
     *
     * @param columns
     * @param order
     * @return DataTableV2
     */
    public DataTableV2 setOrderingColumns(String columns, String order);
}
